config/routes.rb
Rails.application.routes.draw do

  get 'users/index'

  get 'users/show'

  devise_for :users
  root 'root#home'

  controller :root do
    get :home
    get :privacy
    get :about
  end

  resources :rooms

  resources :users, only: [:index, :show] do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :active_relationships, source: :follower

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where.not(id: current_user.id )
  end

  def show
    @users = User.where.not(id: current_user.id )
    @user = User.find(params[:id])
    @room = Room.find_by(owner_id: @user.id)
    @room_user = RoomUser.where(user_id: @user.id)
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_following'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

end

app/helpers/users_helper.rb
module UsersHelper
    def current_user?(user)
        user == current_user
    end
end

app/views/users/_follow.html.erb
<button>
<%= form_for(current_user.active_relationships.build) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit '友達になる', class: 'btn' %>
<% end %>
</button>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div id="follow_form">
        <% if current_user.following?(@user) %>
            <%= render 'unfollow' %>
        <% else %>
            <%= render 'follow' %>
        <% end %>
    </div>
<% end %>

app/views/users/_show_follower.html.erb
<%= @user.followers.each do |user| %>
<div class="show-image">
    <img src="/human_image.jpeg">
</div>
<h3><%= @user.name %></h3>

app/views/users/_show_following.html.erb
<%= @user.followings.each do |user| %>
<div class="show-image">
    <img src="/human_image.jpeg">
</div>
<h3><%= @user.name %></h3>
<% end %>

app/views/users/_unfollow.html.erb
<button>
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
    <%= f.submit "友達解除する", class: 'btn' %>
<% end %>
</button>

app/views/users/_user.html.erb
<div class="chat_list">
    <div class="chat_people">
    <%= link_to user_path(user) do %>
        <div class="chat_img"> <img src="/human_image.jpeg" class="rounded-circle"> </div>
        <div class="chat_ib">
            <% if @room.nil? %>
                <% @room = Room.find_by(owner_id: current_user.id) %>
                <% @message = Message.where(room_id: @room.id).last %>
                <h5><%= user.name %><span class="chat_date"><%= l(@message.created_at, format: :long) %></span></h5>
                <p><%= @message.content %></p>
            <% else %>
                <% @message = Message.where(room_id: @room.id).last %>
                <h5><%= user.name %><span class="chat_date"><%= l(@message.created_at, format: :long) %></span></h5>
                <p><%= @message.content %></p>
            <% end %>
        </div>
    <% end %>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, '友達一覧') %>
<div class="container">
  <div class="messaging">
    <div class="inbox_msg">
      <%= render partial: 'layouts/chat_index'%>
      <div class="container-index text-center">
        <h1>CHATAPP!<h1>
        <h3>プライベートなトーク空間を</h3>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name ) %>
<div class="container">
  <div class="messaging">
    <div class="inbox_msg">
      <%= render partial: 'layouts/chat_index'%>
      <div class="container-show text-center">
        <div class="show-image">
            <img src="/human_image.jpeg">
        </div>
        <h3><%= @user.name %></h3>


        <% if current_user.following?(@user)%>

          <% if @room.present? && @room_user.present? %>

            <% if @room = Room.find_by(owner_id: current_user.id) %>

              <% if @room_user.ids.include?(@room.id) %>
                <%= link_to room_path(@room) do %>
                  <button class="btn btn-talk btn-xs">
                    <h4>トークルームへ</h4>
                  </button>
                <% end %>
              <% elsif @room = Room.where(owner_id: @user.id) %>
              <% @room_user = RoomUser.where(user_id: current_user.id) %>
              <% @room_users = @room & @room_user%>
                <% if @room_users.present? %>
                  <%= link_to room_path(@room) do %>
                  <button class="btn btn-talk btn-xs">
                    <h4>トークルームへ</h4>
                  </button>
                  <% end %>
                <% else %>
                <% @room = Room.where(owner_id: current_user.id) %>
                <% @room_user = RoomUser.where(user_id: @user.id) %>
                <% @room_users = @room.ids & @room_user.ids %>
                  <% if @room_users.present? %>
                    <%= link_to room_path(@room_users) do %>
                      <button class="btn btn-talk btn-xs">
                        <h4>トーク一覧へ</h4>
                      </button>
                    <% end %>
                  <% else %>
                    <%= link_to new_room_path(:user_id => @user.id), :method => 'get' do %>
                      <button class="btn btn-talk btn-xs">
                        <h4>トークルームの作成</h4>
                      </button>
                    <% end %>
                    <%= render 'follow_form' %>
                  <% end %>
                <% end %>
              <% else %>
                <%= link_to new_room_path(:user_id => @user.id), :method => 'get' do %>
                  <button class="btn btn-talk btn-xs">
                    <h4>トークルームの作成</h4>
                  </button>
                <% end %>
                <%= render 'follow_form' %>
              <% end %>
            <% else %>
            <% @room = Room.where(owner_id: @user.id) %>
            <% @room_user = RoomUser.where(user_id: current_user.id) %>
            <% @room_users = @room.ids & @room_user.ids %>
              <% if @room_users.present? %>
                <%= link_to room_path(@room_users) do %>
                  <button class="btn btn-talk btn-xs">
                    <h4>トークルームへ</h4>
                  </button>
                <% end %>
              <% else %>
                <%= link_to new_room_path(:user_id => @user.id), :method => 'get' do %>
                  <button class="btn btn-talk btn-xs">
                    <h4>トークルームの作成</h4>
                  </button>
                <% end %>
                <%= render 'follow_form' %>
              <% end %>
            <% end %>
              

          <% elsif @room.present? %>

          <% @room = Room.where(owner_id: @user.id) %>
          <% @room_user = RoomUser.where(user_id: current_user.id) %>
          <% @room_users = @room.ids & @room_user.ids %>

            <% if @room_users.present? %>
              <%= link_to room_path(@room_user.ids) do %>
                <button class="btn btn-talk btn-xs">
                  <h4>トークルームへ</h4>
                </button>
              <% end %>
            <% else %>
              <%= link_to new_room_path(:user_id => @user.id), :method => 'get' do %>
                <button class="btn btn-talk btn-xs">
                  <h4>トークルームの作成</h4>
                </button>
              <% end %>
              <%= render 'follow_form' %>
            <% end %>


          <% elsif @room.nil? && @room_user.present? %>

          <% @room = Room.where(owner_id: current_user.id) %>
          <% @room_users = @room.ids & @room_user.ids %>
              
            <% if @room_users.present? %>
              <%= link_to room_path(@room_users) do %>
                <button class="btn btn-talk btn-xs">
                  <h4>トークルームへ</h4>
                </button>
              <% end %>
            <% else %>
              <%= link_to new_room_path(:user_id => @user.id), :method => 'get' do %>
                <button class="btn btn-talk btn-xs">
                  <h4>トークルームの作成</h4>
                </button>
              <% end %>
              <%= render 'follow_form' %>
            <% end %>

          <% else %>

            <%= link_to new_room_path(:user_id => @user.id), :method => 'get' do %>
              <button class="btn btn-talk btn-xs">
                <h4>トークルームの作成</h4>
              </button>
           <% end %>

          <% end %>
        <% else %>
          <%= render 'follow_form'%>
        <% end %>
      </div>
    </div>
  </div>
</div>